[package]
name = "maelstorm-demos"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
h2 = "0.4"
maelstrom-node = "0.1.6"
async-trait = "0.1"

[[bin]]
name = "echo"
